### PR TITLE
Fix rubygems.org status check

### PR DESCRIPTION
**Pull request by evanphx**
statuspage.io changed their CSS, so this needs to change too!

### CODE REVIEW

**Comment by TildeWill** [comment]
What about monitoring some part of the status site that isn't DOM/CSS dependent? Suggesting the RSS feed: https://status.rubygems.org/history.rss

**Comment by andistuder** [comment]
AFAIK `histroy.rss` feed does not have the required data to evaluate the current status. Better would to to  query https://status.github.com/api/status.json - this will return something like 
```
{"status":"good","last_updated":"2016-02-05T09:12:28Z"}
```
see docs: https://status.github.com/api

**Comment by Khoulaiz** [comment]
I don't see why the status of github is relevant to this issue. Is there such a json query for rubygems, too?

**Comment by andistuder** [comment]
@Khoulaiz :blush: I mixed something up here, thanks for spotting. But luckily, Rubygems offers a similar service: https://status.rubygems.org/api#status

**Comment by tjgrathwell** [comment]
Fixed in #97 + edf391627a30aeb6d4317070fc8810d8d9bae254

**Pull request closed without merging**
