### PR TITLE
Use MySQL as the database

### PR DESCRIPTION
**Pull request by mjstallard**
As we are standardizing on using MySQL for Pivotal apps hosted on Cloud Foundry, we are changing Project Monitor to use this instead of Postgres.
- MySQL doesn't support default values for `TEXT` fields, so we default the value of `Project#iteration_story_state_counts` in Ruby
- turns out that MySQL's precision for `datetime` values is less than Postgres, so we have to fiddle the `created_at` value in some tests
- MySQL doesn't support `RANK() OVER(PARTITION BY...` style queries, so this has been replaced by a query based on [this Stackoverflow article](http://stackoverflow.com/questions/10881990/rank-function-in-mysql-with-order-by-clause)
# 

I will update this Pull Request once we're running this in production.

### CODE REVIEW

**Comment by mjstallard** [comment]
We can confirm that this is now in production - see http://ci.pivotallabs.com/

**Comment by tjgrathwell** [comment]
@erd @mjstallard re: 043d0de - I don't see the 'simplifying', it looks like you just deleted both the manifests?

Is there a unified ultra-manifest sitting around that you didn't add to git?

If you changed the command used to deploy, https://github.com/pivotal/projectmonitor#deployment should be updated too

**Comment by erd** [comment]
We use one manifest that gets deployed to different spaces. One space for staging, one space for prod, etc. We'll include a doc update tomorrow.

**Comment by erd** [comment]
We've added a workaround for the emoji by using `serialize` for the project's code field. This will cause the field to roundtrip to Marshal, allowing it to be persisted in spite of MySQL.

See https://dev.firmafon.dk/blog/quick-no-hack-emoji-support-with-mysql-rails/ for more details.

This is a quicker/easier way of doing things, rather than adding full emoji support for every table by migrating to `utf8mb4`.

**Comment by professor** [comment]
I'm curious about the status of this pull request.  I've seen emoji's on pulse monitor. Do we still want this code?

**Comment by mjstallard** [comment]
Closing this as I no longer work at Pivotal and I think this is a pretty stale PR by now 🙃

**Pull request closed without merging**
